// Pixel Studio — Gallery: รวมผลงานทั้งหมดเป็นหน้าเดียว (เปิดดู/แชร์/ใส่พอร์ต)
// อ่านไฟล์ที่มีอยู่ (evolution.png · battle.png · leaderboard.json) → gallery.html + gallery-preview.png
// รัน:  node gallery.mjs   (หรือ npm run gallery)
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { chromium } from "playwright";

const has = (f) => existsSync(f);

const lb = has("leaderboard.json") ? JSON.parse(readFileSync("leaderboard.json", "utf8")) : {};
const lbRows = Object.entries(lb)
  .sort((a, b) => b[1].wins - a[1].wins)
  .map(([m, s]) => `<tr class="border-t border-white/10"><td class="py-2 pr-4">${m}</td><td class="pr-4">${s.wins}/${s.runs}</td><td class="pr-4">${Math.round((s.wins / s.runs) * 100)}%</td><td>${(s.totalScore / s.runs).toFixed(1)}</td></tr>`)
  .join("");

const card = (title, sub, img) =>
  has(img)
    ? `<section class="mb-12"><h2 class="text-xl font-bold">${title}</h2><p class="text-neutral-400 text-sm mb-4">${sub}</p><img src="${img}" class="rounded-xl ring-1 ring-white/10 w-full"/></section>`
    : "";

const html = `<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pixel Studio</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-neutral-950 text-white font-sans">
  <div class="max-w-4xl mx-auto px-6 py-14">
    <h1 class="text-4xl md:text-5xl font-black tracking-tight">🎨 Pixel <span class="text-rose-500">Studio</span></h1>
    <p class="text-neutral-400 mt-3 text-lg">ทีม AI หลายโมเดลออกแบบ UI — <b class="text-white">สร้าง · วิจารณ์วนแก้ · ประลอง</b></p>
    <div class="h-px bg-white/10 my-10"></div>
    ${card("🎬 Critic loop", "AI วิจารณ์งานตัวเองจากภาพที่ render จริง แล้ววนแก้จนผ่านเกณฑ์", "evolution.png")}
    ${card("⚔️ Model Battle", "หลายโมเดลแข่งกันออกแบบจาก brief เดียว → vision-critic ตัดสินผู้ชนะ 👑", "battle.png")}
    ${lbRows ? `<section class="mb-12"><h2 class="text-xl font-bold mb-4">📊 Leaderboard</h2>
      <table class="text-sm"><thead class="text-neutral-400 text-left"><tr><th class="pb-2 pr-4">Model</th><th class="pr-4">Wins</th><th class="pr-4">Win-rate</th><th>Avg score</th></tr></thead><tbody>${lbRows}</tbody></table></section>` : ""}
    <p class="text-neutral-600 text-xs mt-10">Generated by Pixel Studio · multi-model AI design studio</p>
  </div>
</body></html>`;
writeFileSync("gallery.html", html, "utf8");

// fullPage screenshot สำหรับแชร์/ใส่พอร์ต
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1000, height: 800 }, deviceScaleFactor: 2 });
await page.goto(pathToFileURL(resolve("gallery.html")).href, { waitUntil: "networkidle" });
await page.waitForTimeout(500);
await page.screenshot({ path: "gallery-preview.png", fullPage: true });
await browser.close();

console.log("✅ gallery.html + gallery-preview.png");
